### ISSUE TITLE
Svelte DevTools shows the "Not Working?" text in Chrome

### ISSUE THREAD

**Issue by xavi7th** [sveltejs/svelte-devtools#38] opened 2021-03-06 10:24 UTC
**Describe the bug**
I just updated to version 3.0.0 of svelte-loader and I noticed that it broke dev tools. When I downgraded back to ^2.13.0 everything works fine.

**To Reproduce**
1. Update to "svelte-loader": "^3.0.0"
2. Build your app in dev mode
3. Open the dev tools
4. You will get the Svelte DevTools Not Working error

**Additional context**
I believe it has to do with this change in the new svelte-loader:  ``` compiler options must now be specified under compilerOptions ```. I have not tested this supposition though.

Thanks for your work with the devtools. It's been so helpful that I am not updating svelte-loader yet for just this reason.

**Comment by nickpoulos** [comment] 2021-04-25 21:21
I can second that I am getting the same error when using svelte-loader 3.1.1.  I have not been able to find a workaround

**Comment by alexanderniebuhr** [comment] 2021-04-27 09:41
same issue using esbuild

**Comment by bershanskiy** [comment] 2021-06-16 06:22
Is this still an issue? If so, could you provide more details? Minimal repro project would be ideal, but if you don't have it, I can look at a real project which breaks for you.

**Comment by xavi7th** [comment] 2021-07-03 13:13
Hello @bershanskiy. Yes this is still an issue for me. If you are ok with it I could add you to a private repo which breaks for me.

I have noticed that using Laravel 8 and the latest Svelte breaks the devtools.

**Comment by bershanskiy** [comment] 2021-07-04 09:21
> If you are ok with it I could add you to a private repo which breaks for me.

Yes, that could help to find root cause and create a minimal reproduction steps.

**Comment by xavi7th** [comment] 2021-07-07 02:48
> > If you are ok with it I could add you to a private repo which breaks for me.
> 
> Yes, that could help to find root cause and create a minimal reproduction steps.

Invite sent. I am available to answer any questions you might have. Thanks once again.

**Comment by nickpoulos** [comment] 2021-08-22 05:24
@bershanskiy any updates here?

**Comment by bershanskiy** [comment] 2021-08-22 22:42
> @bershanskiy any updates here?

Current extension logic is rather odd and requires significant rework to fix all quirks. I created a few PRs, some of which were already merged, and 4 more are still open and unreviewed. At this time, I'm not sure how to proceed to minimize merge conflicts/breakage.

**Closed** 2023-10-03 09:44 UTC
Labels: bug, committed
