### ISSUE TITLE
Can't get working svelte devtools in Chrome with svelte new version 3.46.4

### ISSUE THREAD

**Issue by PhuongTPham** [sveltejs/svelte-devtools#69] opened 2022-03-07 04:44 UTC
**Describe the bug**
I just update svelte latest version: 3.46.4 and dev: true in rollup.config.js. 
But It can't work svelte dev tools in Chrome, I rerun many times and config same as the document: https://github.com/RedHatter/svelte-devtools

**Environment**
- Ubuntu 20.04
- Browser with version: Chrome Version 99.0.4844.51
- Devtools version: 1.3.0
- Svelte version: 3.46.4

![Screenshot from 2022-03-07 11-25-24](https://user-images.githubusercontent.com/40297848/156969075-312a3fd2-b8c1-46d1-bcbd-8ba30ba3bcde.png)
![Screenshot from 2022-03-07 11-39-12](https://user-images.githubusercontent.com/40297848/156969077-1be2d020-f4f9-492e-86a7-6fdcedeee026.png)

**Comment by dominikg** [comment] 2022-03-11 16:02
a user on svelte discord mentioned that it broke for them when updating from chrome 97 to 99 https://discord.com/channels/457912077277855764/728292755087818924/951864005985697872

**Comment by zhengtulymGh** [comment] 2022-03-28 08:00
I have the same problem。

**Environment**
macOS Monterey 12.2.1 (21D62)
Browser with version: 99.0.4844.84（正式版本） (x86_64)
Devtools version: 1.3.0
Svelte version: 3.46.4

**Comment by tbenko73** [comment] 2022-03-29 20:59
Same problem,

on MacOs 12.3
Chrome Version 100.0.4896.60 (Official Build) (x86_64)
Svelte Devtools 1.3.0
Svelte 3.46.7
With rollup 2.7.1

rollup.config.js:
...
plugins:[
 svelte({
      compilerOptions: {
        dev: true
      }
})
]
...

**Comment by zhengtulymGh** [comment] 2022-03-29 20:59
这是来自QQ邮箱的假期自动回复邮件。
 
您好，来件已收到，我会尽快回复您。。。。

**Comment by markawightman75** [comment] 2022-03-31 10:48
Yep, same problem. 

Ubuntu 20.04
Browser with version: Chrome Version 99.0.4844.84
Devtools version: 1.3.0
Svelte version: 3.46.5

Did anyone find a workaround?

**Comment by kenpower** [comment] 2022-04-04 11:57
Same

Windows 10 build 19044.1586
Chrome Version 99.0.4844.74 (Official Build) (64-bit)
devtools 1.3.0
svelte@3.46.4

Last commit in master is 17 June 2021. Is it being actively maintained?

**Comment by ontrack1** [comment] 2022-04-05 18:44
**Solved** (on local machine).

Same issue listed above:
Ubuntu 20.04
svelte 3.42.5
[Version 1.37.111 Chromium: 100.0.4896.79 (Official Build) (64-bit)]

Note in title area now has "PhuongTPham opened this issue on Mar 6 · 6 comments · **May be fixed by 70**"

You all may have this figured out & fixed already, but if not here are the steps:

**prerequisite to steps**: uninstall non-working svelte-devtools extension from your browser

- go to [#70](https://github.com/RedHatter/svelte-devtools/pull/70) (https://github.com/RedHatter/svelte-devtools/pull/70)
- you will note brandonbloom tested fix locally & solved issue
- go to https://github.com/RedHatter/svelte-devtools
- follow instructions on how to **build from source**
- DO **NOT** LOAD quite yet we have 1 more crucial step to make this work.
- go to the [fix](https://github.com/RedHatter/svelte-devtools/pull/70/commits/7edf051cf204e4c9d7b780681aa07cb73e4c3d77)
- copy the new code on line 4
- find this 'src/background.js' file in your local 'dest' file folder
-**MOST CRITICAL STEP** replace the old line 4 with the working version line 4 from the fix
- now you are ready for the last step of the build from source: Load Unpacked--that will need the updated background.js

After installing if you still receive the error message--do the hard refresh/f5click here, if all previous steps were completed, it will go away.

**Comment by Nisthar** [comment] 2022-04-07 11:06
@ontrack1 why isn't this merged yet?

**Comment by vhscom** [comment] 2022-04-23 10:39
Related to or shares root cause with #68 most likely.

**Comment by bershanskiy** [comment] 2022-09-15 21:25
Relevant Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1364293

**Closed** 2023-09-14 09:43 UTC
